#pragma once

enum ApiResponse
{
	OK = 0,
	INVALID_MAGIC_BYTES = 1,
	WRONG_PROTOCOL_VERSION = 2,
	INVALID_REQUEST_TYPE = 3,
	INVALID_REQUEST_LENGTH = 4,
	INVALID_ON_OFF_STATE = 5,
	OUTPUT_DISABLED = 6,
	INVALID_EFFECT_ID = 7,
	INVALID_N_OF_COLORS = 8
};