#pragma once

#define SUCCESS 0
#define INVALID_MAGIC_BYTES 1
#define PROTOCOL_VERSION_MISMATCH 2
#define INVALID_REQUEST_TYPE 3
#define INVALID_REQUEST_LENGTH 4
#define INVALId_ON_OFF_STATE 5
#define OUTPUT_DISABLED 6
#define INVALID_EFFECT_ID 7
#define INVALID_N_OF_COLORS 8
#define CONNECTION_ERROR -1